version: "2"

run:
  go: "1.24"
  tests: false

output:
  formats:
    - format: tab
      path: stdout

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - goconst
    - gocritic

  disable:
    - depguard
    - exhaustruct
    - gosec
    - mnd
    - musttag
    - wsl
    - inamedparam
    - revive
    - funlen
    - gochecknoglobals
    - godot
    - godox
    - ireturn
    - nolintlint
    - nonamedreturns
    - perfsprint
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - intrange

  settings:
    goconst:
      min-len: 2
      min-occurrences: 2

    gocritic:
      enable-all: true
      disabled-checks:
        - ifElseChain
        - whyNoLint

    govet:
      enable:
        - shadow
        - rangevalcopy
