FROM golang:1.24.13-alpine

WORKDIR /app/awesomeProject

COPY go.mod go.sum ./
RUN go mod download

COPY ./ ./
COPY e2e_tests/tests ./e2e_tests/tests

ENV TEST_TAGS=test_e2e

ENTRYPOINT ["sh", "-c", "go test --tags=${TEST_TAGS} -v -failfast ./e2e_tests/tests/..."]
